Data.table
hugheylab/deltaccd pull request #3
Opened 2021-04-27 20:51 UTC by ehoutland

- modified the calcCCD, calcDeltaCCD, and calcCorr functions to use data.tables instead of data.frames/tidyverse objects
- added an optional argument to scale CCDs by number gene pairs to calcCCD
- modified calcDeltaCCDSimple function to call the calcCCDSimple function instead of recalculating CCDs

2021-04-28 13:16 UTC, jakejh requested changes
Also in the DESCRIPTION file:
- update Version to 0.2
- Add yourself as aut, see pmparser for example

2021-04-28 13:16 UTC, jakejh commented on DESCRIPTION
> +  tidyr (>= 0.7.2),
remove tidyr dependency, use data.table instead.

2021-04-28 13:16 UTC, jakejh commented on R/deltaccd.R
> +  if (scale) {
use `isTRUE`

2021-04-28 13:16 UTC, jakejh commented on R/deltaccd.R
> +  nPairs = ncol(genePairs)
The calculation of nPairs can be simplified to one line, and doesn't need to use colnames or combn. See `?Special`.

2021-04-28 13:16 UTC, jakejh commented on R/deltaccd.R
> +    return(calcDist(corVecRef, corVecTest)/nPairs)
Reduce redundancy in the if statement, such that the call to calcDist is only on one line, and the return statement is after the if statement.

2021-04-28 13:16 UTC, jakejh commented on R/deltaccd.R
> +        method = method, scale = scale)
Adjust indention so that method aligns with refNow. RStudio should've done this automatically.

2021-04-28 13:16 UTC, jakejh commented on R/deltaccd.R
> +      data.table::data.table(group = groupNow, CCD = ccdObs, Pvalue = NA)}}
Add an importFrom statement at the top of the file that lets you use `data.table` everywhere instead of `data.table::data.table`.

2021-04-28 13:16 UTC, jakejh commented on R/deltaccd_plot.R
> +  dt1 = data.table::data.table(stats::cor(as.matrix(dt[, geneNames])
Fix the awkward line breaks and indention. Lines should not start with a comma.

2021-04-28 13:16 UTC, jakejh commented on R/deltaccd_plot.R
> +    dtTmp = calcCorrSimple(dt[group == group], method = method)
`group == group` does not mean what you think it means. You have to rename the variable to distinguish it from the column.

2021-04-28 13:16 UTC, jakejh commented on R/deltaccd_plot.R
> +  dtFinal = dtFinal[
I think two separate lines, each using `:=` in the conventional way, would be more readable.

2021-04-28 13:16 UTC, jakejh commented on R/deltaccd_plot.R
> +  dt = data.table::melt
?

2021-04-28 13:16 UTC, jakejh commented on R/deltaccd_plot.R
> +  dt[
Same comment as before.

2021-04-28 13:16 UTC, jakejh commented on R/deltaccd_plot.R
>    cLims = calcColorLimits(df$rho)
These lines are still using df instead of dt. Good example of not having a test.

2021-04-28 13:16 UTC, jakejh commented on R/deltaccd_plot.R
> +  p = plotHeatmapSimple(ggplot2::ggplot(dt) + ggplot2::facet_wrap(~ group),
While we're at it, we might as well update the call to facet_wrap to use the currently recommended syntax, which uses `vars` instead of a formula.

2021-04-28 14:29 UTC, jakejh requested changes

2021-04-28 14:29 UTC, jakejh commented on R/deltaccd_plot.R
> +  dtFinal = dtFinal[, gene1 = factor(gene1, rownames(ematNow))]
Incorrect syntax. Wouldn't have passed testing.

2021-04-28 14:29 UTC, jakejh commented on R/deltaccd_plot.R
> +  p = plotHeatmapSimple(ggplot2::ggplot(dt) + ggplot2::facet_wrap(vars(group)),
Are you sure you don't need `ggplot2::vars`?

2021-04-28 14:29 UTC, jakejh commented on R/deltaccd_plot.R
> +  dt[, gene2 = factor(gene2, rev(rownames(ematNow))))]
Incorrect syntax.

2021-04-28 14:29 UTC, jakejh commented on R/deltaccd.R
> +  if(isTRUE(scale)) {
add whitespace after if

2021-04-28 14:42 UTC, JSchoenbachler commented
https://github.com/hugheylab/deltaccd/blob/75495dc3744b9a8a6a54f8f32a39a923a965d642/R/deltaccd.R#L45-L59

I know this wasn't necessarily in your scope of moving to use data.table, but this function seems to reference global variables rather than accepting them as inputs (specifically the `refCorMouseEntrez`). Maybe @jakejh could chime in here in case I'm missing something, but it might be better to accept that as an input to the function than to rely on it already being a variable.

2021-04-28 14:46 UTC, JSchoenbachler commented
https://github.com/hugheylab/deltaccd/blob/75495dc3744b9a8a6a54f8f32a39a923a965d642/NAMESPACE#L12

You might want to run a check locally and push to update the NAMESPACE file, you are still importing `%>%` from magrittr and the `data.table` import is missing.

2021-04-28 15:01 UTC, JSchoenbachler commented on R/deltaccd.R
>      result = foreach(groupNow = sort(unique(groupVec)), .combine = rbind) %do% {
Not going to do this for all, but just like with `if` statements, don't we add a space after `foreach` @jakejh ? I could be wrong.

2021-04-28 15:24 UTC, JSchoenbachler requested changes
Agree with Jakes points, with a few additional comments of my own.

2021-04-28 15:31 UTC, jakejh commented
Re Josh's comments:
- our convention is to add space after `if`, but not after `foreach`, since the latter is a normal function call.
- `refCorMouseEntrez` is not a global variable, it's a dataset within the package. See https://r-pkgs.org/data.html

2021-04-28 15:32 UTC, JSchoenbachler commented
Gotcha, will remove those comments!

2021-04-28 15:32 UTC, JSchoenbachler commented on R/deltaccd.R
>      result = foreach(groupNow = sort(unique(groupVec)), .combine = rbind) %do% {
Resolving because I was mistaken.

2021-04-28 16:05 UTC, jakejh commented
@ehoutland I'm guessing you have not run `devtools::check`. There are a few issues you still need to address.

2021-04-28 16:24 UTC, ehoutland commented
> @ehoutland I'm guessing you have not run `devtools::check`. There are a few issues you still need to address.

Oops, I hadn't done that. I think I've resolved most of the notes from `devtools::check` now. The only one that's left is on installed size, but that's just because of the data-set (GSE19188) that comes with the package, right?

2021-04-28 17:32 UTC, JSchoenbachler commented
What size is the package now? Its not significantly larger than the 22.2 MB currently, right?

2021-04-28 17:40 UTC, ehoutland commented
No, not much bigger. It's 22.8 MB now.

2021-04-28 19:10 UTC, jakejh requested changes
Once everything is addressed, make sure to update the NEWS file and run `pkgdown::build_site`.

2021-04-28 19:10 UTC, jakejh commented on R/deltaccd_plot.R
> +  dtFinal = dtFinal[, gene1 := factor(gene1, rownames(ematNow))]
`:=` changes by reference, so simplify these

2021-04-28 19:10 UTC, jakejh commented on R/deltaccd.R
> +                  'rho', 'group2Now', 'geneNames', 'ematNow', 'dt1'))
are you sure you want `dt1` as a global variable? look at where you're using it.

2021-04-28 19:10 UTC, jakejh commented on R/deltaccd.R
> +      ccdRand = doOp (foreach(ii = 1:nPerm, .combine = c), {
no space needed after `doOp`

2021-04-28 19:54 UTC, ehoutland commented
Just ran `pkgdown::build_site`. Should the installation and usage sections be on the site preview? I'm not seeing them.

2021-04-28 20:48 UTC, jakejh commented
Compare it against https://deltaccd.hugheylab.org

2021-04-28 21:10 UTC, ehoutland commented
It seems like pkgdown cares whether the name of the readme file is 'readme.md' vs 'README.md'. It built the homepage from the right file once I changed the name.

2021-04-28 21:21 UTC, jakejh requested changes
- There are still at least three instances of a line starting with a comma. That just won't do.
- While we're at it, let's change the `ifelse` statements to use the preferred `doOp = if (a) x else y` syntax.

2021-04-28 21:21 UTC, jakejh commented on R/deltaccd.R
> +#' registerDoParallel(cores )
?

2021-04-30 19:39 UTC, jakejh commented
Have you tested calcCorrSimple? When I try it, I get a series of errors.

2021-05-03 14:40 UTC, jakejh commented
- The `getRefCor` function needs to be able to return the human blood reference with gene symbols instead of entrez gene ids, depending on the `useEntrezGeneId` argument.
- Make sure to use the short-circuit `||` instead of vectorized `|` (and `&&` instead of `&`) in `if` statements.

2021-05-03 18:38 UTC, jakejh commented
Now see if you can remove two sources of redundancy in `getRefCor`:
- construction of the `colname` variable (three lines should be sufficient)
- assignment of `colnames(ref)`

2021-05-04 19:58 UTC, merged